services:
  calorie-tracker-db:
    image: mysql:8.3
    container_name: calorie-tracker-db
    environment:
      - MYSQL_DATABASE=calorie_tracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 13306:3306
    restart: unless-stopped
