volumes:
  calorie-tracker-data:

services:
  calorie-tracker-db:
    image: mysql:8.3
    container_name: calorie-tracker-db
    environment:
      - MYSQL_DATABASE=calorie_tracker
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
  calorie_tracker:
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    container_name: calorie_tracker
    volumes:
      - ./:/app
    ports:
      - 8989:3000
